### ISSUE TITLE
how to set fan speed!?

### ISSUE THREAD

**Issue by StormCh** [CodeFoodPixels/robovac#39]
Hi, I'd like to set fan speed via automation.

is this the correct way?

```
      - service: vacuum.set_fan_speed
        data:
          fan_speed: Pure
        target:
          device_id: XYZ

```

Thanks for reply!
