### ISSUE TITLE
X8 lost connection

### ISSUE THREAD

**Issue by Diondk** [CodeFoodPixels/robovac#91]
Hi,

now since a week of 2 my x8 lost connection to HA, i have reinstalled the integration but its still not working

I have enabled logging:

```
logger:
  # default: debug
  logs:
    custom_components.robovac.vacuum: debug
    custom_components.robovac.tuyalocalapi: debug
```
but the log files dont show anything. and when i go to integration eufy robovac i see that the x8 is unavailable.

Any tips on how i get the logs?

Kr,
Dion
